/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ApiHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CollectorHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "EventsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "InfoProcessingDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "InfoProcessingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MarketInfoTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ProjectInfoTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ProjectsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SourceConfigTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}