import type {
  Project,
  DashboardSummary,
  ProjectStatus,
  NewsSentiment,
  ProjectCategory,
} from '@crypto-dashboard/shared';

// Mock data for development and initial testing
export const mockProjects: Project[] = [
  {
    id: 'binance',
    name: 'Binance',
    logo: 'https://assets.coingecko.com/markets/images/52/small/binance.jpg',
    website: 'https://binance.com',
    twitter: 'binance',
    category: 'cex',
    description: 'The world\'s largest cryptocurrency exchange by trading volume',
    status: 'normal',
    healthScore: 85,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'neutral',
    recentEvents: [
      {
        id: '1',
        date: new Date(Date.now() - 86400000).toISOString(),
        title: 'Binance Launches New Trading Feature',
        description: 'Binance introduces advanced order types for professional traders',
        source: 'CoinDesk',
        sentiment: 'positive',
        eventType: 'product',
      },
    ],
    riskFlags: [],
    opportunityFlags: [
      {
        type: 'product_launch',
        importance: 'medium',
        description: 'New institutional trading features',
        detectedAt: new Date().toISOString(),
      },
    ],
    coingeckoId: 'binance',
    attributes: {
      dailyVolume: 15000000000,
      dailyVolumeChange24h: 5.2,
      reservesTransparency: 'full',
      proofOfReserves: true,
      regulatoryStatus: 'licensed',
      supportedCountries: ['Global'],
      tradingPairs: 1500,
      spotVolume: 8000000000,
      derivativesVolume: 7000000000,
    },
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    logo: 'https://assets.coingecko.com/markets/images/23/small/Coinbase_Coin_Primary.png',
    website: 'https://coinbase.com',
    twitter: 'coinbase',
    category: 'cex',
    description: 'US-based regulated cryptocurrency exchange',
    status: 'watch',
    healthScore: 78,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'positive',
    recentEvents: [
      {
        id: '2',
        date: new Date(Date.now() - 172800000).toISOString(),
        title: 'Coinbase Reports Strong Q4 Earnings',
        description: 'Trading volume and revenue exceed expectations',
        source: 'The Block',
        sentiment: 'positive',
        eventType: 'news',
      },
    ],
    riskFlags: [],
    opportunityFlags: [
      {
        type: 'regulatory_approval',
        importance: 'high',
        description: 'Expanded regulatory compliance in EU',
        detectedAt: new Date().toISOString(),
      },
    ],
    coingeckoId: 'coinbase',
    attributes: {
      dailyVolume: 3500000000,
      dailyVolumeChange24h: 12.5,
      reservesTransparency: 'full',
      proofOfReserves: true,
      regulatoryStatus: 'licensed',
      supportedCountries: ['US', 'EU', 'UK'],
      tradingPairs: 500,
      spotVolume: 3500000000,
      derivativesVolume: 0,
    },
  },
  {
    id: 'uniswap',
    name: 'Uniswap',
    logo: 'https://assets.coingecko.com/coins/images/12504/small/uniswap.png',
    website: 'https://uniswap.org',
    twitter: 'Uniswap',
    category: 'dex',
    description: 'Leading decentralized exchange on Ethereum',
    status: 'normal',
    healthScore: 88,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'positive',
    recentEvents: [],
    riskFlags: [],
    opportunityFlags: [
      {
        type: 'major_upgrade',
        importance: 'high',
        description: 'Uniswap V4 development progress',
        detectedAt: new Date().toISOString(),
      },
    ],
    coingeckoId: 'uniswap',
    defillamaId: 'uniswap',
    attributes: {
      dailyVolume: 1500000000,
      dailyVolumeChange24h: -2.3,
      reservesTransparency: 'full',
      regulatoryStatus: 'unlicensed',
      tradingPairs: 3000,
      spotVolume: 1500000000,
      tvl: 5500000000,
      tvlChange24h: 1.2,
      tvlChange7d: 5.5,
      auditStatus: 'audited',
      auditors: ['Trail of Bits', 'OpenZeppelin'],
      tokenSymbol: 'UNI',
      tokenPrice: 7.85,
      tokenMarketCap: 5900000000,
      chains: ['Ethereum', 'Polygon', 'Arbitrum', 'Optimism', 'Base'],
      category: 'DEX',
    },
  },
  {
    id: 'aave',
    name: 'Aave',
    logo: 'https://assets.coingecko.com/coins/images/12645/small/AAVE.png',
    website: 'https://aave.com',
    twitter: 'aaboratory',
    category: 'defi',
    description: 'Decentralized lending and borrowing protocol',
    status: 'normal',
    healthScore: 92,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'positive',
    recentEvents: [
      {
        id: '3',
        date: new Date(Date.now() - 259200000).toISOString(),
        title: 'Aave V3 Reaches $10B TVL',
        description: 'Milestone reached across all deployed chains',
        source: 'DefiLlama',
        sentiment: 'positive',
        eventType: 'news',
      },
    ],
    riskFlags: [],
    opportunityFlags: [
      {
        type: 'ecosystem_growth',
        importance: 'high',
        description: 'GHO stablecoin adoption growing',
        detectedAt: new Date().toISOString(),
      },
    ],
    defillamaId: 'aave',
    attributes: {
      tvl: 12500000000,
      tvlChange24h: 2.1,
      tvlChange7d: 8.3,
      auditStatus: 'audited',
      auditors: ['OpenZeppelin', 'Trail of Bits', 'Certora'],
      exploitHistory: [],
      tokenSymbol: 'AAVE',
      tokenPrice: 95.50,
      tokenMarketCap: 1400000000,
      chains: ['Ethereum', 'Polygon', 'Avalanche', 'Arbitrum', 'Optimism'],
      category: 'Lending',
    },
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    logo: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    website: 'https://ethereum.org',
    twitter: 'ethereum',
    category: 'layer1',
    description: 'The leading smart contract platform',
    status: 'normal',
    healthScore: 95,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'positive',
    recentEvents: [],
    riskFlags: [],
    opportunityFlags: [],
    coingeckoId: 'ethereum',
    attributes: {
      tps: 30,
      blockTime: 12,
      activeAddresses24h: 500000,
      activeAddresses7d: 2500000,
      developerActivity: 95,
      ecosystemSize: 4000,
      tvl: 55000000000,
      tokenSymbol: 'ETH',
      tokenPrice: 2450,
      tokenMarketCap: 295000000000,
      consensusMechanism: 'Proof of Stake',
    },
  },
  {
    id: 'solana',
    name: 'Solana',
    logo: 'https://assets.coingecko.com/coins/images/4128/small/solana.png',
    website: 'https://solana.com',
    twitter: 'solana',
    category: 'layer1',
    description: 'High-performance blockchain for DeFi and NFTs',
    status: 'watch',
    healthScore: 82,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'positive',
    recentEvents: [
      {
        id: '4',
        date: new Date(Date.now() - 432000000).toISOString(),
        title: 'Solana DeFi TVL Surges',
        description: 'DeFi ecosystem sees significant growth',
        source: 'The Block',
        sentiment: 'positive',
        eventType: 'news',
      },
    ],
    riskFlags: [],
    opportunityFlags: [
      {
        type: 'ecosystem_growth',
        importance: 'high',
        description: 'Rapid DeFi and NFT ecosystem expansion',
        detectedAt: new Date().toISOString(),
      },
    ],
    coingeckoId: 'solana',
    attributes: {
      tps: 4000,
      blockTime: 0.4,
      activeAddresses24h: 800000,
      activeAddresses7d: 3000000,
      developerActivity: 88,
      ecosystemSize: 800,
      tvl: 4500000000,
      tokenSymbol: 'SOL',
      tokenPrice: 98,
      tokenMarketCap: 42000000000,
      consensusMechanism: 'Proof of History + Proof of Stake',
    },
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum',
    logo: 'https://assets.coingecko.com/coins/images/16547/small/photo_2023-03-29_21.47.00.jpeg',
    website: 'https://arbitrum.io',
    twitter: 'arbitrum',
    category: 'layer2',
    description: 'Leading Ethereum Layer 2 scaling solution',
    status: 'normal',
    healthScore: 87,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'positive',
    recentEvents: [],
    riskFlags: [],
    opportunityFlags: [],
    defillamaId: 'arbitrum',
    attributes: {
      tps: 40000,
      blockTime: 0.25,
      activeAddresses24h: 200000,
      activeAddresses7d: 800000,
      developerActivity: 85,
      ecosystemSize: 500,
      tvl: 2800000000,
      tokenSymbol: 'ARB',
      tokenPrice: 0.85,
      tokenMarketCap: 2700000000,
      consensusMechanism: 'Optimistic Rollup',
      chains: ['Ethereum'],
    },
  },
  {
    id: 'circle-usdc',
    name: 'USDC (Circle)',
    logo: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png',
    website: 'https://circle.com',
    twitter: 'circle',
    category: 'stablecoin',
    description: 'Fully-reserved USD stablecoin by Circle',
    status: 'normal',
    healthScore: 94,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'neutral',
    recentEvents: [],
    riskFlags: [],
    opportunityFlags: [],
    coingeckoId: 'usd-coin',
    attributes: {
      marketCap: 25000000000,
      circulatingSupply: 25000000000,
      pegDeviation: 0.001,
      backingType: 'fiat',
      reserveComposition: { 'US Treasuries': 80, 'Cash': 20 },
      attestationFrequency: 'Monthly',
      chains: ['Ethereum', 'Solana', 'Polygon', 'Arbitrum', 'Base'],
    },
  },
  {
    id: 'tether',
    name: 'Tether (USDT)',
    logo: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
    website: 'https://tether.to',
    twitter: 'Tether_to',
    category: 'stablecoin',
    description: 'Largest stablecoin by market cap',
    status: 'watch',
    healthScore: 72,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'neutral',
    recentEvents: [],
    riskFlags: [
      {
        type: 'regulatory_risk',
        severity: 'medium',
        description: 'Ongoing regulatory scrutiny',
        detectedAt: new Date().toISOString(),
      },
    ],
    opportunityFlags: [],
    coingeckoId: 'tether',
    attributes: {
      marketCap: 95000000000,
      circulatingSupply: 95000000000,
      pegDeviation: 0.0005,
      backingType: 'hybrid',
      reserveComposition: { 'US Treasuries': 65, 'Other': 35 },
      attestationFrequency: 'Quarterly',
      chains: ['Ethereum', 'Tron', 'Solana', 'Polygon', 'Arbitrum'],
    },
  },
  {
    id: 'metamask',
    name: 'MetaMask',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/3/36/MetaMask_Fox.svg',
    website: 'https://metamask.io',
    twitter: 'MetaMask',
    category: 'wallet',
    description: 'Leading self-custody crypto wallet',
    status: 'normal',
    healthScore: 88,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'neutral',
    recentEvents: [],
    riskFlags: [],
    opportunityFlags: [],
    attributes: {
      userCount: 30000000,
      transactionVolume: 1000000000,
      supportedChains: ['Ethereum', 'Polygon', 'BSC', 'Arbitrum', 'Optimism', 'Avalanche'],
      securityFeatures: ['Hardware wallet support', 'Phishing detection', 'Transaction simulation'],
    },
  },
  {
    id: 'wintermute',
    name: 'Wintermute',
    website: 'https://wintermute.com',
    twitter: 'wintermute_t',
    category: 'market_maker',
    description: 'Leading algorithmic trading firm and market maker',
    status: 'normal',
    healthScore: 80,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'neutral',
    recentEvents: [],
    riskFlags: [],
    opportunityFlags: [],
    attributes: {
      aum: 500000000,
      trackRecord: 'Founded 2017, active in 50+ exchanges',
      counterpartyExposure: ['Binance', 'OKX', 'Bybit', 'Uniswap'],
      strategies: ['Market Making', 'Arbitrage', 'OTC Trading'],
    },
  },
  {
    id: 'moonpay',
    name: 'MoonPay',
    logo: 'https://www.moonpay.com/assets/logo-full-white.svg',
    website: 'https://moonpay.com',
    twitter: 'moonaboratory',
    category: 'payment',
    description: 'Crypto on/off ramp solution',
    status: 'normal',
    healthScore: 85,
    lastUpdated: new Date().toISOString(),
    newsSentiment: 'positive',
    recentEvents: [],
    riskFlags: [],
    opportunityFlags: [
      {
        type: 'partnership',
        importance: 'medium',
        description: 'New partnerships with major brands',
        detectedAt: new Date().toISOString(),
      },
    ],
    attributes: {
      transactionVolume: 5000000000,
      supportedCurrencies: ['USD', 'EUR', 'GBP', 'AUD', 'CAD'],
      supportedCountries: ['US', 'EU', 'UK', 'AU', 'CA'],
      regulatoryLicenses: ['MSB (US)', 'FCA (UK)'],
      fundingRounds: [
        {
          date: '2022-11-01',
          round: 'Series A',
          amount: 555000000,
          valuation: 3400000000,
          investors: ['Tiger Global', 'Coatue', 'Paradigm'],
        },
      ],
    },
  },
];

export const mockDashboardSummary: DashboardSummary = {
  totalProjects: mockProjects.length,
  byCategory: {
    cex: 2,
    dex: 1,
    market_maker: 1,
    payment: 1,
    layer1: 2,
    layer2: 1,
    defi: 1,
    wallet: 1,
    infrastructure: 0,
    stablecoin: 2,
  },
  byStatus: {
    normal: 9,
    watch: 3,
    warning: 0,
    danger: 0,
  },
  recentAlerts: mockProjects
    .flatMap((p) => p.recentEvents)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, 5),
  topGainers: [
    { project: mockProjects[1], change: 12.5 },
    { project: mockProjects[5], change: 8.3 },
  ],
  topLosers: [
    { project: mockProjects[2], change: -2.3 },
  ],
  lastUpdated: new Date().toISOString(),
};

export function getProjectsByCategory(category: ProjectCategory): Project[] {
  return mockProjects.filter((p) => p.category === category);
}

export function getProjectById(id: string): Project | undefined {
  return mockProjects.find((p) => p.id === id);
}

export function getProjectsByStatus(status: ProjectStatus): Project[] {
  return mockProjects.filter((p) => p.status === status);
}

export function searchProjects(query: string): Project[] {
  const lowerQuery = query.toLowerCase();
  return mockProjects.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.description?.toLowerCase().includes(lowerQuery) ||
      p.category.toLowerCase().includes(lowerQuery)
  );
}
